import PDFDocument from "pdfkit";
import type { ExportIncomeRow } from "@/lib/export/incomeDocuments";
import { summarizeIncomeRows } from "@/lib/export/incomeDocuments";
import {
  SCHEDULE_C_PART_II_LINES,
  sumExportAmountsByLineKey,
} from "@/lib/export/scheduleCLines";
import type { ExportExpenseRow } from "@/lib/tax/exportRows";

export type ScheduleCMirrorPdfInput = {
  taxYear: string;
  taxpayerName: string;
  businessIndustry: string;
  auditRows: ExportExpenseRow[];
  incomeRows: ExportIncomeRow[];
};

const DISCLAIMER =
  "Notice: This is a compiled expense report generated by Snap1099 based on your uploaded receipts. It is NOT an official tax return. Use these numbers to fill out Part II of your official IRS Form 1040 (Schedule C).";

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

function appendixRows(auditRows: ExportExpenseRow[]): ExportExpenseRow[] {
  const groups = new Map<string, ExportExpenseRow[]>();
  for (const row of auditRows) {
    const key = row.scheduleCLine || "Line 27a";
    const list = groups.get(key) ?? [];
    list.push(row);
    groups.set(key, list);
  }
  const sorted: ExportExpenseRow[] = [];
  for (const line of SCHEDULE_C_PART_II_LINES) {
    const rows = groups.get(line.label);
    if (!rows?.length) continue;
    rows.sort((a, b) => b.dateIso.localeCompare(a.dateIso));
    sorted.push(...rows);
  }
  return sorted;
}

export async function buildScheduleCMirrorPdf(
  input: ScheduleCMirrorPdfInput,
): Promise<Buffer> {
  const { taxYear, taxpayerName, businessIndustry, auditRows, incomeRows } =
    input;
  const lineTotals = sumExportAmountsByLineKey(auditRows);
  const incomeSummary = summarizeIncomeRows(incomeRows);
  let line28Total = 0;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: "LETTER" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).font("Helvetica-Bold").text(`Tax Year ${taxYear}`);
    doc.moveDown(0.5);
    doc.fontSize(10).font("Helvetica");
    doc.text(`Taxpayer Name: ${taxpayerName}`);
    doc.text(`Business/Industry: ${businessIndustry}`);
    doc.moveDown(0.5);
    doc.fontSize(8).fillColor("#444444").text(DISCLAIMER);
    doc.fillColor("#000000").moveDown(1);

    doc.fontSize(12).font("Helvetica-Bold").text("Part II — Expenses");
    doc.moveDown(0.5);
    doc.fontSize(9).font("Helvetica-Bold");
    doc.text("Line", { continued: true, width: 70 });
    doc.text("Description", { continued: true, width: 280 });
    doc.text("Amount", { align: "right" });
    doc.moveDown(0.3);
    doc.font("Helvetica");

    for (const line of SCHEDULE_C_PART_II_LINES) {
      const amount = round2(lineTotals.get(line.key) ?? 0);
      line28Total += amount;
      doc.text(line.label, { continued: true, width: 70 });
      doc.text(line.irsLabel, { continued: true, width: 280 });
      doc.text(`$${amount.toFixed(2)}`, { align: "right" });
    }

    doc.moveDown(0.3);
    doc.font("Helvetica-Bold");
    doc.text("Line 28", { continued: true, width: 70 });
    doc.text("Total expenses", { continued: true, width: 280 });
    doc.text(`$${round2(line28Total).toFixed(2)}`, { align: "right" });
    doc.font("Helvetica").moveDown(1);

    doc.fontSize(11).font("Helvetica-Bold").text("Part I — Income");
    doc.moveDown(0.4);
    doc.fontSize(10).font("Helvetica");
    if (incomeRows.length === 0) {
      doc.text(
        "No 1099 forms captured yet — snap 1099-NEC / 1099-K from Export to add income.",
      );
    } else {
      doc.text(
        `Line 1 · Gross receipts or sales: $${incomeSummary.totalGross.toFixed(2)} (${incomeSummary.formCount} forms)`,
      );
      doc.text(
        `Line 7 · Gross Income: $${incomeSummary.totalGross.toFixed(2)}`,
      );
    }
    doc.moveDown(1);

    doc.fontSize(11).font("Helvetica-Bold").text("Appendix — Expense Detail");
    doc.moveDown(0.4);
    doc.fontSize(8).font("Helvetica");

    for (const row of appendixRows(auditRows)) {
      doc.font("Helvetica-Bold").text(
        `${row.dateIso} · ${row.merchant} · $${row.exportAmount.toFixed(2)}`,
      );
      doc.font("Helvetica").text(
        `${row.scheduleCLine || "Line 27a"} · ${row.categoryDisplay}${row.notes ? ` · ${row.notes}` : ""}`,
      );
      if (row.auditIndex) {
        doc.fillColor("#444444").text(
          `Image Ref: ${row.auditIndex}${row.auditImagePath ? ` · ${row.auditImagePath}` : ""}`,
        );
        doc.fillColor("#000000");
      }
      doc.moveDown(0.35);
    }

    if (incomeRows.length > 0) {
      doc.moveDown(0.5);
      doc.fontSize(11).font("Helvetica-Bold").text("1099 Income Forms");
      doc.moveDown(0.3);
      doc.fontSize(8).font("Helvetica");
      for (const row of incomeRows) {
        doc.text(
          `${row.dateIso} · ${row.formType} · ${row.payer} · $${row.amount.toFixed(2)}`,
        );
        doc.fillColor("#444444").text(`Document: ${row.incomeArchivePath}`);
        doc.fillColor("#000000");
        doc.moveDown(0.25);
      }
    }

    doc.end();
  });
}
