import { PDFDocument, StandardFonts, rgb, type PDFPage } from "pdf-lib";
import { LEGAL_BRAND_NAME } from "@/lib/legal/operator";
import type { ExportIncomeRow } from "@/lib/export/incomeDocuments";
import { summarizeIncomeRows } from "@/lib/export/incomeDocuments";
import {
  SCHEDULE_C_PART_II_LINES,
  sumExportAmountsByLineKey,
} from "@/lib/export/scheduleCLines";
import type { ExportExpenseRow } from "@/lib/tax/exportRows";
import type { ScheduleCMirrorPdfInput } from "@/lib/export/buildScheduleCMirrorPdf";

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 48;

const DISCLAIMER =
  `Notice: This is a compiled expense report generated by ${LEGAL_BRAND_NAME} based on your uploaded receipts. It is NOT an official tax return. Use these numbers to fill out Part II of your official IRS Form 1040 (Schedule C).`;

/** StandardFonts WinAnsi: replace chars pdf-lib cannot encode (CJK, emoji, etc.). */
export function toPdfSafeText(text: string): string {
  let out = "";
  for (const char of text) {
    const code = char.charCodeAt(0);
    if (code >= 0x20 && code <= 0xff) {
      out += char;
    } else if (char === "\n" || char === "\r" || char === "\t") {
      out += char;
    } else {
      out += "?";
    }
  }
  return out;
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

function appendixRows(auditRows: ExportExpenseRow[]): ExportExpenseRow[] {
  const groups = new Map<string, ExportExpenseRow[]>();
  for (const row of auditRows) {
    const key = row.scheduleCLine || "Line 27a";
    const list = groups.get(key) ?? [];
    list.push(row);
    groups.set(key, list);
  }
  const sorted: ExportExpenseRow[] = [];
  for (const line of SCHEDULE_C_PART_II_LINES) {
    const rows = groups.get(line.label);
    if (!rows?.length) continue;
    rows.sort((a, b) => b.dateIso.localeCompare(a.dateIso));
    sorted.push(...rows);
  }
  return sorted;
}

type PdfWriter = {
  doc: PDFDocument;
  page: PDFPage;
  yTop: number;
  regular: Awaited<ReturnType<PDFDocument["embedFont"]>>;
  bold: Awaited<ReturnType<PDFDocument["embedFont"]>>;
};

async function createWriter(): Promise<PdfWriter> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  return { doc, page, yTop: MARGIN, regular, bold };
}

function yFromTop(writer: PdfWriter, size: number): number {
  return PAGE_HEIGHT - writer.yTop - size;
}

function ensureSpace(writer: PdfWriter, needed: number): PDFPage {
  if (writer.yTop + needed <= PAGE_HEIGHT - MARGIN) return writer.page;
  writer.page = writer.doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  writer.yTop = MARGIN;
  return writer.page;
}

function drawText(
  writer: PdfWriter,
  text: string,
  opts: {
    size?: number;
    bold?: boolean;
    color?: ReturnType<typeof rgb>;
    lineHeight?: number;
    x?: number;
  } = {},
): void {
  const size = opts.size ?? 10;
  const lineHeight = opts.lineHeight ?? size * 1.25;
  ensureSpace(writer, lineHeight);
  writer.page.drawText(toPdfSafeText(text), {
    x: opts.x ?? MARGIN,
    y: yFromTop(writer, size),
    size,
    font: opts.bold ? writer.bold : writer.regular,
    color: opts.color ?? rgb(0, 0, 0),
  });
  writer.yTop += lineHeight;
}

function drawLineRow(
  writer: PdfWriter,
  line: string,
  description: string,
  amount: string,
  bold = false,
): void {
  const size = 9;
  const lineHeight = size * 1.25;
  ensureSpace(writer, lineHeight);
  const y = yFromTop(writer, size);
  const font = bold ? writer.bold : writer.regular;
  writer.page.drawText(toPdfSafeText(line), { x: MARGIN, y, size, font });
  writer.page.drawText(toPdfSafeText(description), { x: MARGIN + 70, y, size, font });
  const amountWidth = font.widthOfTextAtSize(amount, size);
  writer.page.drawText(toPdfSafeText(amount), {
    x: PAGE_WIDTH - MARGIN - amountWidth,
    y,
    size,
    font,
  });
  writer.yTop += lineHeight;
}

/** Browser-compatible Schedule C mirror PDF (pdf-lib). */
export async function buildBrowserScheduleCMirrorPdf(
  input: ScheduleCMirrorPdfInput,
): Promise<Uint8Array> {
  const { taxYear, taxpayerName, businessIndustry, auditRows, incomeRows } =
    input;
  const lineTotals = sumExportAmountsByLineKey(auditRows);
  const incomeSummary = summarizeIncomeRows(incomeRows);
  let line28Total = 0;

  const writer = await createWriter();

  drawText(writer, `Tax Year ${taxYear}`, { size: 20, bold: true });
  drawText(writer, `Taxpayer Name: ${taxpayerName}`);
  drawText(writer, `Business/Industry: ${businessIndustry}`);
  drawText(writer, DISCLAIMER, {
    size: 8,
    color: rgb(0.27, 0.27, 0.27),
    lineHeight: 10,
  });
  writer.yTop += 8;

  drawText(writer, "Part II — Expenses", { size: 12, bold: true });
  drawLineRow(writer, "Line", "Description", "Amount", true);
  for (const line of SCHEDULE_C_PART_II_LINES) {
    const amount = round2(lineTotals.get(line.key) ?? 0);
    line28Total += amount;
    drawLineRow(
      writer,
      line.label,
      line.irsLabel,
      `$${amount.toFixed(2)}`,
    );
  }
  drawLineRow(
    writer,
    "Line 28",
    "Total expenses",
    `$${round2(line28Total).toFixed(2)}`,
    true,
  );
  writer.yTop += 8;

  drawText(writer, "Part I — Income", { size: 11, bold: true });
  if (incomeRows.length === 0) {
    drawText(writer, "No 1099 forms captured yet — snap 1099-NEC / 1099-K from Export to add income.", {
      size: 10,
    });
  } else {
    drawText(
      writer,
      `Line 1 · Gross receipts or sales: $${incomeSummary.totalGross.toFixed(2)} (${incomeSummary.formCount} forms)`,
      { size: 10 },
    );
    drawText(
      writer,
      `Line 7 · Gross Income: $${incomeSummary.totalGross.toFixed(2)}`,
      { size: 10 },
    );
  }
  writer.yTop += 8;

  drawText(writer, "Appendix — Expense Detail", { size: 11, bold: true });
  for (const row of appendixRows(auditRows)) {
    drawText(
      writer,
      `${row.dateIso} · ${row.merchant} · $${row.exportAmount.toFixed(2)}`,
      { size: 8, bold: true },
    );
    drawText(
      writer,
      `${row.scheduleCLine || "Line 27a"} · ${row.categoryDisplay}${row.notes ? ` · ${row.notes}` : ""}`,
      { size: 8 },
    );
    if (row.auditIndex) {
      drawText(
        writer,
        `Image Ref: ${row.auditIndex}${row.auditImagePath ? ` · ${row.auditImagePath}` : ""}`,
        { size: 8, color: rgb(0.27, 0.27, 0.27) },
      );
    }
    writer.yTop += 4;
  }

  if (incomeRows.length > 0) {
    writer.yTop += 8;
    drawText(writer, "1099 Income Forms", { size: 11, bold: true });
    for (const row of incomeRows) {
      drawText(
        writer,
        `${row.dateIso} · ${row.formType} · ${row.payer} · $${row.amount.toFixed(2)}`,
        { size: 8 },
      );
      drawText(writer, `Document: ${row.incomeArchivePath}`, {
        size: 8,
        color: rgb(0.27, 0.27, 0.27),
      });
      writer.yTop += 4;
    }
  }

  return writer.doc.save();
}
